# Generated by Django 5.1.2 on 2024-10-27 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="images/")),
                ("title", models.CharField(max_length=200)),
                ("description", models.CharField(max_length=200)),
                ("github_link", models.CharField(max_length=200)),
                ("linkedin_link", models.CharField(default="", max_length=200)),
                ("category", models.CharField(default="", max_length=200)),
            ],
        ),
    ]
